# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbd4673b0b3ba04136f16780ae0e4550be4c33eea84deacf78b1a6e4542b16bb77f7fe86c0a6eced40c049c0f2416bbe02efe0d46f4f9f019940c575a18b11af

test:
  secret_key_base: d2e42eac9a7cb9c931f0f09e1ab0aa3f199073757a64a245e14128d9891c92544fbbd3ad2fb44d87c7aea835778091134fdcf734c815d42f6c4e20eb097469c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
